.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. doichain_qt test_doichain_qt
clean: FORCE
	$(MAKE) -C .. doichain_qt_clean test_doichain_qt_clean
check: FORCE
	$(MAKE) -C .. test_doichain_qt_check
doichain-qt doichain-qt.exe: FORCE
	 $(MAKE) -C .. doichain_qt
